### ISSUE TITLE
Doesn't work in Rails 3.2.0.rc1!

### ISSUE THREAD

**Issue by parndt** [svenfuchs/routing-filter#31]
I get this lovely error:

/Users/parndt/.rvm/gems/ruby-1.9.3-p0/gems/routing-filter-0.2.4/lib/routing_filter/adapters/rails_3.rb:17:in 'filters': undefined method 'filters' for #Journey::Routes:0x007fa7b5ad2d98 (NoMethodError)
